services:
  kong:
    image: kong:3.4
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - '8000:8000' # Proxy port
      - '8001:8001' # Admin API port
    volumes:
      - ./kong:/usr/local/kong/declarative
    networks:
      - kong-network

  backend:
    build: ./backend
    environment:
      - PORT=8002
      - DEBUG=False
      - AWS_REGION=eu-north-1
      - BEDROCK_MODEL_ID=eu.anthropic.claude-3-7-sonnet-20250219-v1:0
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=sales_chatbot
      - DB_USER=postgres
      - DB_PASSWORD=password
      - CRM_API_URL=https://api.example-crm.com/v1
      - VECTOR_DB_NAMESPACE=product_data
      - DEV_MODE=False
    ports:
      - '8002:8002'
    networks:
      - kong-network

networks:
  kong-network:
    driver: bridge
